name: Generate Electron artifacts
# TODO: Get versions from package.json
# TODO: Add windows-2022 when fixed: bin\pnpm.cjs: %1 is not a valid Win32 application.
on:
  pull_request:
    types: [closed]
    branches:
      - generate-electron-artifacts

jobs:
  publish-electron-artifacts:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
  
    runs-on: ${{ matrix.os }}
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.0'

      - name: Install pnpm
        uses: pnpm/action-setup@v3

        
      - name: Fix pnpm.cjs
        if: matrix.os == 'windows-2022'
        env:
          PNPM_CJS: C:/Users/runneradmin/setup-pnpm/node_modules/.pnpm/pnpm@9.5.0/node_modules/pnpm/bin/pnpm.cjs
        run: |
          cat $PNPM_CJS
          sed -i 's/#!\/usr\/bin\/env node/#!node/' $PNPM_CJS
          cat $PNPM_CJS
    
      
      - name: Build electron
        run: pnpm electron:build
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: electron-artifacts
          path: |
            builds/*/*.*
            !builds/*/*.yaml
            !builds/*/*.yml
            !.icon-set
            !*.blockmap